"""add_bank_balance_to_accounts

Revision ID: 192e271a5632
Revises: 5011067e481d
Create Date: 2026-06-17 09:13:30.086742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '192e271a5632'
down_revision: Union[str, Sequence[str], None] = '5011067e481d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('bank_balance', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('accounts', sa.Column('bank_balance_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'bank_balance_at')
    op.drop_column('accounts', 'bank_balance')
    # ### end Alembic commands ###
