"""add_recurring_rules

Revision ID: 32bca214c8d9
Revises: f072b2436cfc
Create Date: 2026-06-15 06:58:35.004030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32bca214c8d9'
down_revision: Union[str, Sequence[str], None] = 'f072b2436cfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('kind', sa.Enum('income', 'expense', name='rr_kind'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.Enum('weekly', 'monthly', 'yearly', name='rr_frequency'), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_rules_household_id'), 'recurring_rules', ['household_id'], unique=False)
    op.create_index(op.f('ix_recurring_rules_next_date'), 'recurring_rules', ['next_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_rules_next_date'), table_name='recurring_rules')
    op.drop_index(op.f('ix_recurring_rules_household_id'), table_name='recurring_rules')
    op.drop_table('recurring_rules')
    # ### end Alembic commands ###
