"""add_bank_sync_log

Revision ID: 427ebfdac78e
Revises: 75028a2b6f3a
Create Date: 2026-06-17 08:15:43.587972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427ebfdac78e'
down_revision: Union[str, Sequence[str], None] = '75028a2b6f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('household_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('accounts_found', sa.Integer(), nullable=False),
    sa.Column('txns_created', sa.Integer(), nullable=False),
    sa.Column('txns_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_sync_logs_household_id'), 'bank_sync_logs', ['household_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bank_sync_logs_household_id'), table_name='bank_sync_logs')
    op.drop_table('bank_sync_logs')
    # ### end Alembic commands ###
